spring:
  application:
    name: application-dev
  profiles:
    active: dev
  ai:
    openai:
      api-key: sk-f4b7b1cd0d864b1ca32a73fd681176ba





server:
  port: 8080


logging:
  level:
    root: INFO
    org.dingdang: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 雪花算法
idworker:
  worker-id: 1
  datacenter-id: 1

wechat:
  appid: wxd1d04e884923f52e
  secret: b2b11d4e1cbd8f91db2144e803732ba1

llm:
  qwen:
    api-key: sk-f4b7b1cd0d864b1ca32a73fd681176ba