name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # 你可以选择其他JDK发行版，比如 'zulu' 或 'adopt'
        java-version: '22'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # 使用相同的JDK发行版
        java-version: '22'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
